### ISSUE TITLE
Read count normalization

### ISSUE THREAD

**Issue by C-Janssen** [mikessh/vdjtools#100]
Hi Mikhail, or other users,

I have a question about normalization in the basic analysis:
My experiment: I entered my RNAseq data to MiXCR, and used this output for VDJtools.
Analysing 2 populations of T-cells, I noticed the read count was significantly lower in my 2nd group. (The cells isolated for RNAseq were also lower for this 2nd group, though cDNA amplification was performed, so RNAseq total reads (via Cook’s distance) do not show any difference between the samples of the 2 groups.)
So I was wondering if for the calculation of clonotype diversity; there is a correction for read count? Or is the read count difference I’m seeing a ‘real’ specific cell characteristic?
Mikhail mentions in Pre-processing:
_Note -Most of routines specified in this section will output processed clonotype tables and re-normalize individual clonotype frequencies by dividing their read count by the total read count in resulting (filtered/processed) sample._

So are Diversity, mean_frequency and geomean_frequency Basicstats already corrected for read count? If not, then what is the best way to correct for this, should I normalize to RNA input?

Thanks for any clarification!
Kind regards,
Janssen

**Comment by mikessh** [comment]
Dear Janssen,

Normalization is a complex issue especially for small datasets, so 1,000-10,000 can often lack information to perform diversity estimates, especially in cases when mostly naive cells are present (singletons). The overall number of TCR/BCR reads is also a measure to consider: see our recent Nat Biotechnol paper and melanoma patient survival prediction. In your case you can try running ``CalcDiversityStats`` with ``--downsample-to`` set to smallest sample size, so you can get estimates and standard deviation for your larger sample produced by in-silico re-sampling.

As for BasicStats - they contain values computed directly and do not properly account for sample size. I.e. given typical clonotype frequency distribution one cannot simply divide the number of unique clonotypes by total number of reads to obtain a proper estimate (series of down-sampling/rarefaction is need in this case).

Hope this helps,
Best regards,
Mike

**Comment by C-Janssen** [comment]
Dear Mike,
Thanks so much! I will definitely follow your advice and try downsampling of the samples. 
The paper is a useful example- makes sense to extract random reads, an equal amount for all samples to use these for comparing the diversity - thanks!

Kind regards,
Janssen
