### ISSUE TITLE
R packages installed with different internals error

### ISSUE THREAD

**Issue by SolaimanR** [mikessh/vdjtools#111]
Ive seen similar problems here that have been solved in issue #71 and #72 , however, those solutions didnt work for me. I get following error when I run anything that needs to plot something. For example:

`$VDJTOOLS PlotFancySpectratype `

This will give me following Error and halt the script:

```
[ERROR] Loading required package: ggplot2
Error: package or namespace load failed for ‘ggplot2’:
 package ‘scales’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Loading required package: reshape
Error: package or namespace load failed for ‘reshape’:
 package ‘reshape’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Loading required package: RColorBrewer
Error in melt(df, id = "Len") : could not find function "melt"
Execution halted
```
Now I have tried everything I could think of, from removing R and reinstalling it from scratch to manually installing every required R package. I can start these packages when I run R in console or from Rstudio.

Only one thing worked, but cant be used by us. When I install R 3.1.0 it works. However, then many many other important packages dont work for us because they require at least 3.1.2, and then VDJTOOLS doesnt work again. 

What is this issue? What am I missing?

**Comment by mikessh** [comment]
This seems to be a problem with R packages on your side. I think the best way to solve it is to re-install R, make sure you clean the contents of R libraries folder & VDJtools R package folder and re-install all of them. Some of the packages installed were built with older R version and are incompatible with current R version.
