### ISSUE TITLE
why my RarefactionPlot ouput haven't  Shaded areas (mark 95% confidence intervals)

### ISSUE THREAD

**Issue by lanyuchunmo** [mikessh/vdjtools#112]
I got a plot of rarefaction analysis, but my plot is somewhat different from the one in the tutorial, there no shade area in my plot. why?
![image](https://user-images.githubusercontent.com/31131817/49851527-539ae680-fe1c-11e8-8aec-9c7388f195af.png)

**Comment by mikessh** [comment]
Hello,

It is likely that at this sample size the actual standard deviation is very small compared to diversity values, so while the shaded area is there, it is completely hidden by the rarefaction curve
