### ISSUE TITLE
mixcr input Convert for vdjtools

### ISSUE THREAD

**Issue by ibseq** [mikessh/vdjtools#115]
Hi, 
trying to follow the instructions :"Output from MiXCR software export routine in full (default) mode can be used without any pre-processing.
Run Convert routine with -S mixcr argument to prepare datasets in this format for VDJtools analysis."

which output from mixcr is suppsed to be used for -S Convert?
I have .vdjca and .clns

thnks
ib

**Comment by GildasLepennetier** [comment]
I think you have to use the .clns, because clonotype information is required. But I guess you already tried both and found out.

**Comment by ibseq** [comment]
Hi, 
Actually none of them was working this is why I asked. I re-run mixcr and yes, I used .clna
Is there a difference if I use .clns?

Thanks

**Comment by dbolotin** [comment]
Hi,

Use txt (tab-delimited) output. E.g. output of:

```
mixcr exportClones clones.clns clones.txt
```

You can also export clones to txt from `clna` (clones and alignments container format) files.

**Comment by ibseq** [comment]
Thanks Dmitry. 
Sorted

BW
Irene
