### ISSUE TITLE
Question about hydropathy

### ISSUE THREAD

**Issue by moj85** [mikessh/vdjtools#116]
I am wondering which hydropathy scale is used for calculating AA hydropathy in the CalcCdrAAProfile and Annotate commands. Kyle and Doolittle? I am also wondering whether the capability to examine particular positions in the CDR3 is possible (currently it appears that junctional regions as well as the central 5 AA's of the CDR3 subregion can be examined.) Thank you!

**Comment by mikessh** [comment]
Hello,

You can see the actual property table with references here: https://github.com/mikessh/vdjtools/blob/master/src/main/resources/profile/aa_property_table.txt

We use Kyte-Doolitle scale and the features are identical to those recommended by IMGT (http://www.imgt.org/IMGTeducation/Aide-memoire/_UK/aminoacids/IMGTclasses.html)

**Comment by moj85** [comment]
Thank you!

**Comment by moj85** [comment]
One more question -- I can't seem to obtain stats on the CDR3 amino acid volume (it seems as though it was available in the CalcCdrAAProfile command, but is no longer available in the new CalcCdrAAStats command). Can this parameter be assessed by a different command?

**Comment by mikessh** [comment]
Seems strange, any parameter from the https://github.com/mikessh/vdjtools/blob/master/src/main/resources/profile/aa_property_table.txt should be accessible. Please check the help for the command you use as there is an option to list a comma-separated list of features to compute
