### ISSUE TITLE
CDR3 amino acid physical properties

### ISSUE THREAD

**Issue by mikessh** [mikessh/vdjtools#28]
* Implement calculation of CDR3 aa property profiles using various amino acid groupings that are based on their physical properties
  * Basic properties: polar/non-polar, etc
  * Kidera factors

**Comment by vadimnazarov** [comment]
Also Atchley factors: http://m.pnas.org/content/102/18/6395.long

**Comment by mikessh** [comment]
@vadimnazarov those seem to be mostly protein-DNA interaction-related, they are more suitable for studying transcription factor binding, etc, but I'll check them out, thx :)
