### ISSUE TITLE
Implement management of "unresolved" v d j families

### ISSUE THREAD

**Issue by jbengler** [mikessh/vdjtools#33]
We have ImmunoSeq datasets containing the value "unresolved" in the columns `v`, `d`or `j`.
In case this occurs at least once in `v` and `d` this causes the `facyvj` plot to fail.

I think the reason is line 75 of `vj_pairing_plot.r`. This line `grid.col = c(rcols, ccols)` causes a vector with two occurrences of "unresolved" (One from `v` and one from `d`). Upon transformation to a factor this messes up the blotting.

However, you could also argue that filtering "unresolved" before analyzing would be the preferred way to go anyway. This is just to let you know that we ran into this problem.

All the best and tanks a lot for this amazing piece of software!

**Comment by mikessh** [comment]
Thanks a lot for your feedback! I've fixed it in develop branch, will add it to next release. Needless to say that all R-based plotting needs lots of refactoring. Ideally, there should be a separate R and python-based API to operate with VDJtools output.
As for your second point, I don't think filtering those clonotypes is a good point. For other software formats, there is unlikely to be any clonotype calls in case V segment is not defined, so it is ok to filter such entries. However, the example ImmunoSeq datasets I've seen have many clonotype entries with undefined V/J segments, so filtering them can result in somewhat biased results.

**Comment by jbengler** [comment]
I totally agree that filtering "unresolved" comes with the danger of biased results. So the honest way to do this, would be to include unresolved families in the plots. However, at the moment vdjtools is running to an error, when unresolved V and J are present. This is true for all of my ImmunoSeq samples, one of them I attached below for you to test.

One way to solve this problem I put into a pull request to `vj_pairing_plot.r`. Maybe you come up with a better solution, though.

In fact, as it is currently vdjtools will fail to put out VJ-circos plots with most ImmunoSeq samples.
[5.P1_m4.fancyvj.wt.txt](https://github.com/mikessh/vdjtools/files/87415/5.P1_m4.fancyvj.wt.txt)

**Comment by mikessh** [comment]
I completely agree. Has the #33 fix helped to resolve this issue? Note that I've made it in ``develop`` branch.

**Comment by jbengler** [comment]
Yes, your fix is working for me! Thanks a lot for the quick handling!

Just one little suggestion: I would prefer the labels to be `V.unresolved` and `J.unresolved` because it it easier to understand than `Vunresolved` and `Junresolved`.
