### ISSUE TITLE
ApplySampleAsFilter routine - negative filtering fails

### ISSUE THREAD

**Issue by stevedaley** [mikessh/vdjtools#38]
When running the ApplySampleAsFilter routine, I get the same output whether or not I include "-e" or "--negative" in [options]. I am running vdjtools-1.0.6 Any advice would be much appreciated.

**Comment by mikessh** [comment]
Hello @stevedaley !

It appears that I've already fixed this in 37956e11826d90adcb4a0db48448801772961e59
Please switch to v 1.0.7 where it should work with ``-e`` option right now.

**Comment by stevedaley** [comment]
Thanks Mikhail,
Steve

On 23 February 2016 at 13:01, Mikhail Shugay <notifications@github.com>
wrote:

> Hello @stevedaley <https://github.com/stevedaley> !
>
> It appears that I've already fixed this in 37956e1
> <https://github.com/mikessh/vdjtools/commit/37956e11826d90adcb4a0db48448801772961e59>
> Please switch to v 1.0.7 where it should work with -e option right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikessh/vdjtools/issues/38#issuecomment-187479586>.
>



-- 
-- 


*Stephen Daley*

Senior Research Fellow

Department of Biochemistry and Molecular Biology

School of Biomedical Sciences

Faculty of Medicine, Nursing & Health Sciences

A: 19 Innovation Walk
    Monash University
    3800  VIC
    Australia

T: +613 9905 4399 | M: 0420 304 255

E: stephen.daley@monash.edu

P Please consider the environment before printing this e-mail

ABN 12 377 614 012 CRICOS Provider No 00008C

*This e-mail (including all attachments) is intended for the named
recipient only.  If you receive this e-mail in error, please inform the
sender immediately by reply e-mail.  Also, because the unauthorised use,
storage, disclosure or copying of this e-mail (including attachments) may
be unlawful, please delete the e-mail (and attachments) from your system
and destroy any copies.  If you are the intended recipient of this
e-mail, please consult the original author before any disclosure, copying
or distribution, if this is not explicitly permitted.*
