### ISSUE TITLE
Overlap statistics

### ISSUE THREAD

**Issue by Kinoubi** [mikessh/vdjtools#42]
Hi everybody !
I am using VDJTools for RNA-seq analysis but I am not good in informatic of mathematic or statistic. I am just a biologist :)
So i am asking how the "relative overlap diversity" is measured ? Because I was thinking this value should be really different of similarity index, but it seems that they follow the same variations when I overlap my samples...
Thank in advance for the answer.

Best regards

**Comment by mikessh** [comment]
Hello,

I assume you've seen the formulas from http://vdjtools-doc.readthedocs.io/en/latest/overlap.html#calcpairwisedistances

The relative overlap diversity is the share of unique clonotypes between two samples normalized to the product of diversity in sample1 and sample2. This normalization is quite empirical and means the total number of pairs of clonotypes that are compared between samples.

Depending on your task, other similarity measures listed in documentation can suit you better, i.e. you have to try all of them (CalcPairwiseDistances provides all of them in a single run.

**Comment by Kinoubi** [comment]
‎I have saw them. I just do not understand maths at all :)

Thank you for the explanation anyway. It helps !

Best regards

Karine Bourgade
De: Mikhail Shugay
Envoyé: vendredi 17 juin 2016 16:26
À: mikessh/vdjtools
Répondre à: mikessh/vdjtools
Cc: Kinoubi; Author
Objet: Re: [mikessh/vdjtools] Overlap statistics (#42)


Hello,

I assume you've seen the formulas from http://vdjtools-doc.readthedocs.io/en/latest/overlap.html#calcpairwisedistances

The relative overlap diversity is the share of unique clonotypes between two samples normalized to the product of diversity in sample1 and sample2. This normalization is quite empirical and means the total number of pairs of clonotypes that are compared between samples.

Depending on your task, other similarity measures listed in documentation can suit you better, i.e. you have to try all of them (CalcPairwiseDistances provides all of them in a single run.

---
