### ISSUE TITLE
Error on R step

### ISSUE THREAD

**Issue by qw1mb0** [mikessh/vdjtools#54]
Hello all.
I install vdjtools 1.2 on my server via root. 
But if my users run this tool they got error:

> $ /srv/dna_tools/vdjtools-1.1.1/vdjtools CalcSegmentUsage -m /shared/vdjtools/CalcSegmentUsage/input/metadata.txt -p -f age -n /shared/vdjtools/CalcSegmentUsage/output/2
> 
> [RUtil] Executing Rscript vexpr_plot.r /shared/vdjtools/CalcSegmentUsage/output/2.segments.wt.V.txt 48 0 3 TRUE /shared/vdjtools/CalcSegmentUsage/output/2.segments.wt.V.pdf
> [ERROR] Loading required package: gplots
> 
> Attaching package: ‘gplots’
> 
> The following object is masked from ‘package:stats’:
> 
> ```
> lowess
> ```
> 
> Loading required package: RColorBrewer
> Loading required package: ggplot2
> Loading required package: plotrix
> 
> Attaching package: ‘plotrix’
> 
> The following object is masked from ‘package:gplots’:
> 
> ```
> plotCI
> ```
> 
> Error in pdf(fname) : 
>   cannot open file '/shared/vdjtools/CalcSegmentUsage/output/2.segments.wt.V.pdf'
> Calls: custom.dev -> pdf
> Execution halted
> 
> [RUtil] Executing Rscript vexpr_plot.r /shared/vdjtools/CalcSegmentUsage/output/2.segments.wt.J.txt 13 0 3 TRUE /shared/vdjtools/CalcSegmentUsage/output/2.segments.wt.J.pdf
> [ERROR] Loading required package: gplots
> 
> Attaching package: ‘gplots’
> 
> The following object is masked from ‘package:stats’:
> 
> ```
> lowess
> ```
> 
> Loading required package: RColorBrewer
> Loading required package: ggplot2
> Loading required package: plotrix
> 
> Attaching package: ‘plotrix’
> 
> The following object is masked from ‘package:gplots’:
> 
> ```
> plotCI
> ```
> 
> Error in pdf(fname) : 
>   cannot open file '/shared/vdjtools/CalcSegmentUsage/output/2.segments.wt.J.pdf'
> Calls: custom.dev -> pdf
> Execution halted

All files on tool folder have permission 777 .
vdjtools Rinstall run corretcly and install packages on tool folder Rpackages. When i Run tool via root it's all ok.
Why this error got?

**Comment by mikessh** [comment]
Dear Andrew, thanks for your feedback!. As of 1.0.9 vdjtools stores R scripts together with analysis results. Can you try running the command, un-commenting argument line in the R script that is generated and running this R script from a user (``Rscript script_name.R``). This should tell whether there are problems with Vdjtools ``execute()`` calls or with ``Rscript`` itself.
