### ISSUE TITLE
How does VDJTools determine non-coding clonotypes

### ISSUE THREAD

**Issue by jfong361** [mikessh/vdjtools#60]
Given that VDJTools' input format only has
* count
* freq
* cdr3nt
* cdr3aa
* v
* d
* j
* VEnd
* Dstart
* DEnd
* Jstart
how does the [FilterNonFunctional](http://vdjtools-doc.readthedocs.io/en/latest/preprocess.html#filternonfunctional) routine filter out non-coding **__receptor sequence__**? Looking into the table, the only column revealing whether or not a clonotype is functional is the CDR3aa sequence (those with * has stop codons etc..). Does this mean that FilterNonFunctional only filters non-coding clonotypes based on CDR3 region, and not the whole sequence itself, hence, the [CalcBasicStats](http://vdjtools-doc.readthedocs.io/en/latest/basic.html#calcbasicstats) routine's nc_frequency/diversity denotes the freq/diversity of non-coding CDR3, **__not__** sequences as a whole? 
Further, does this mean that clone annotation coming from [MiGMAP](https://github.com/mikessh/migmap) should **__not__** have the flag `--allow-noncoding` if we were to take into consideration of the whole sequence, as VDJTools only looks at CDR3 region?

**Comment by mikessh** [comment]
Hello,

You are correct: the non-functional status is determined only by ``cdr3aa`` at this moment, so it is better to remove any non-coding V alleles when running V-D-J mapping software.

The parser actually sets a non-functional flag if available in the input (e.g. migmap, immunoseq have a specific column for this), however, this flag is lost after conversion to VDJtools format. This can be reworked in future.

**Comment by jfong361** [comment]
Thanks for the confirmation
