### ISSUE TITLE
vdjtools slow initialization -- issue in parallel execution

### ISSUE THREAD

**Issue by carandraug** [mikessh/vdjtools#61]
We already have a system for batch jobs (we just use GNU make) and so
prefer to perform multiple calls to vdjtools, one per input file, for
cheap parallelisation and for distribution over a cluster.

When we did his, we noticed a massive slowndown.  What took less than
2 minutes (when listing all the files in a single shell command), was
now predicted to take over 3 hours (~4000 files).

I understand that there could be a performance hit and that
initializing the JVM can be an issue.  However, I didn't expect
something of this scale.  Is there anything in the design of vjdtools
that could be the reason for this?

**Comment by mikessh** [comment]
The only thing that comes to my mind is that a big part of VDJtools is written in groovy, so there is some overhead in loading all classes.

Calling vdjtools -h

```
real	0m2.279s
user	0m1.252s
sys	0m0.084s
```

Calling [MAGERI](https://github.com/mikessh/mageri) software that has a relatively huge binary and is written in pure java

```
real	0m0.221s
user	0m0.124s
sys	0m0.020s
```

---

What do you think @dbolotin ?

**Comment by carandraug** [comment]
Ok, I thought the issue would be obvious for someone who wrote vdjtools which is why I didn't measure it properly first. Since it is not, maybe the issue is one my side.  I tested the following which shows that starting vdjtools alone takes ~ 10 seconds on this system:

```
+ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

real    0m0.052s
user    0m0.043s
sys     0m0.014s

+ java -jar vdjtools-1.1.1/vdjtools.jar -h

real    0m11.189s
user    0m1.001s
sys     0m1.425s

+ java hello # a minimal hello world java program to test JVM initialization

real    0m0.061s
user    0m0.047s
sys     0m0.018s
```

The times above where measured on a CentOS 6 system.  I then tested on Debian Stretch (current Debian testing) and vdjtools took roughly 1 second to print its help text. That is much better than 10 seconds but I would still argue that 1 second just to start is too much. When one has thousands of sequence files, that's a lot of seconds.

I also tried measuring the time when processing 1, 2, 3, and 4 files.  In 10 repetitions, the difference between those was negligible, which would indicate that the startup dominates.  However, I understand that vdjtools seems to be doing some parallelization, and if all files are being processed at the same time then this would be pointless. Still, here it is:

    FILES()
    {
      printf "sample-%s-clones.txt \n" $(seq 1 $1);
    }
    VDJTOOLS()
    {
        java -jar vdjtools.jar \
             Convert -S MiXcr \
             $(FILES $1) ./cn > /dev/null
    }

    ## warm up
    for N in {1..10}; do $(VDJTOOLS 4); done

    for T in 4 3 2 1; do
      echo "With $T files"
      time for N in {1..10}; do $(VDJTOOLS $T); done
    done

Which outputted

```
With 4 files
real    3m26.106s
user    1m11.037s
sys     0m22.706s
With 3 files
real    3m25.978s
user    1m9.433s
sys     0m22.726s
With 2 files
real    3m27.688s
user    1m10.543s
sys     0m22.611s
With 1 files
real    3m26.981s
user    1m11.069s
sys     0m22.457s
```

**Comment by mikessh** [comment]
> I thought the issue would be obvious for someone who wrote vdjtools 

Never encountered it before. The typical setup we're using is to run VDJtools for a huge batch of samples on a single server as is, so this is negligible compared with the time required to read 1mln+ clonotype samples.

> That is much better than 10 seconds but I would still argue that 1 second just to start is too much.

Same for me, 1 second on average. I suggest that the 1 second issue is due to the overhead of Groovy framework. The limiting step in JVM startup time is loading the classes from the JAR. Even after some cleanup (see https://github.com/mikessh/vdjtools/commit/20c6ef81f2deabc7dcb119a83db7f4c8b38ebf90) I cannot get much improvement of the startup time.

Also, as I'm running this from my laptop I can see that the JVM startup time greatly depends on overall load from other applications.

> However, I understand that vdjtools seems to be doing some parallelization, and if all files are being processed at the same time then this would be pointless ...

The IO steps are not run in parallel and Convert is a pure IO routine. Try this with smth like CalcBasicStats.

**Comment by carandraug** [comment]
>> I thought the issue would be obvious for someone who wrote vdjtools
>
> Never encountered it before. The typical setup we're using is to run
> VDJtools for a huge batch of samples on a single server as is, so
> this is negligible compared with the time required to read 1mln+
> clonotype samples.

Even on a single server Make has advantages.  You would simply run
`make -jX` and you get X jobs in parallel.  It works with all
programs.  Neat, elegant, and well recognized (to not say standard).
Obviously it assumes startup time to be negligible in the scale of
each job which I know is not always the case.  The same logic would
apply to any build system, I just happen to favour make.

Having to generate a metadata file (or list all files in a single
call), would greatly complicate things.  I'm not even sure if this
will be possible because then vdjtools analysis will have a
prerequesite on the pre-processing of all samples.  I will have to
think better about this, any advice would be welcome.

>> That is much better than 10 seconds but I would still argue that 1
>> second just to start is too much.
>
> Same for me, 1 second on average. I suggest that the 1 second issue
> is due to the overhead of Groovy framework. The limiting step in JVM
> startup time is loading the classes from the JAR. Even after some
> cleanup (see 20c6ef8) I cannot get much improvement of the startup
> time.

I escalated the issue to our sysadmin and turns out that BeeGFS has an
issue with jar files.  On another machine, where this issue was more
accentuated and `vdjtools -h` alone took 1 minute (!!!), we changed
filesystem and it now takes half a second.

This is a lot better, but half second multiplied by thousands is still
not ideal.  I understand you are limited by the language and there's
nothing you can do.  I will prepare patch for documentation.

>> However, I understand that vdjtools seems to be doing some
>> parallelization, and if all files are being processed at the same
>> time then this would be pointless ...
>
> The IO steps are not run in parallel and Convert is a pure IO
> routine. Try this with smth like CalcBasicStats.

Then `Convert` was perfect for the test.  It shows that for small
number of files, startup time of vdjtools was dominating.

**Comment by carandraug** [comment]
> This is a lot better, but half second multiplied by thousands is still
> not ideal. I understand you are limited by the language and there's
> nothing you can do. I will prepare patch for documentation.

Please consider pulling cset 51658454123f7be36bc213.

**Comment by carandraug** [comment]
> The limiting step in JVM startup time is loading the classes from the JAR. Even after some cleanup (see 20c6ef8) I cannot get much improvement of the startup time.

I built that from source, and I too didn't notice much difference:

```
$ time for I in {1..100}; do java -version 2&> /dev/null; done

real	0m5.345s
user	0m4.014s
sys	0m1.496s
$ time for I in {1..100}; do java -jar vdjtools-1.1.4-579176dd.jar > /dev/null; done

real	0m47.350s
user	0m55.757s
sys	0m3.163s
$ time for I in {1..100}; do java -jar vdjtools-1.1.5-9f49a9b2.jar > /dev/null; done

real	0m47.726s
user	0m57.166s
sys	0m3.224s
$ time for I in {1..100}; do grep --help > /dev/null; done

real	0m0.098s
user	0m0.000s
sys	0m0.036s
```

**Comment by mikessh** [comment]
I've modified the docs to highlight this issue.

To sum up:

* The loading overhead is due to usage of Groovy-dependent code in JAR (checked it independently)
* VDJtools way to handle the batch samples is due to the fact that most "interesting" and time-consuming operations require cross-sample analysis: overlapping multiple samples, pooling samples, etc. Although I agree that being cmake-friendly is a big plus I'm not planning to fix (i.e. rewrite Groovy parts in Java) the original VDJtools, but I'll consider this in the future :)
