### ISSUE TITLE
How to upgrade vdjtools with homebrew

### ISSUE THREAD

**Issue by suntaosimon** [mikessh/vdjtools#64]
I want to upgrade to the latest version. 

Thanks!

**Comment by mikessh** [comment]
Hello!

Please refer to homebrew manual [here](https://github.com/Homebrew/brew/blob/master/docs/FAQ.md)

You can try to 
```
brew upgrade <formula>
```

If this doesn't work, you can uninstall the vdjtools formula and then reinstall it as described [here](https://github.com/Homebrew/brew/blob/master/docs/FAQ.md#how-do-i-uninstall-a-formula)
