### ISSUE TITLE
Problem with Mixcr parsing 

### ISSUE THREAD

**Issue by muktad** [mikessh/vdjtools#65]
Hi I am getting the following error when I try to parse MIXCR txt file output. 

Muktas-MacBook-Pro-8:TCR muk$ VDJTOOLS Convert -Smixcr lib12799-.txt L1013
Executing com.antigenomics.vdjtools.misc.Convert -Smixcr lib12799-.txt L1013
[Tue Mar 28 11:10:10 PDT 2017 Convert] Reading sample(s)
[Tue Mar 28 11:10:10 PDT 2017 Convert] 1 sample(s) loaded
[Tue Mar 28 11:10:10 PDT 2017 SampleStreamConnection] Loading sample lib12799-
[ERROR] java.lang.RuntimeException: Unable to parse clonotype string 0	51	0.0446584938704028	TGTGCCTTGTTTCTATATTATAAGAAACTCTTT	NNNNNNNNNNNNNNNNNNNNNNNNNNNNIIIII	TRGV9*00(133.4)		TRGJ1*00(165),TRGJ2*00(165)		348|358|386|0|10||50.0		24|42|70|15|33||90.0;24|42|70|15|33||90.0												TGTGCCTTGTTTCTATATTATAAGAAACTCTTT	40								CALFLYYKKLF		:::::::::0::10:::::15::33::: for MiXcr input type: Some mandatory columns are absent in the input file., see _vdjtools_error.log for details

Can you please help?

**Comment by mikessh** [comment]
There was an issue with mixcr/vdjtools version incompatibility, are you using both the latest mixcr and vdjtools version (see release section of both repos)?

**Comment by muktad** [comment]
I used MiXCR v2.0.3 and VDJ v1.1.4.

**Comment by mikessh** [comment]
This is not the latest mixcr version, https://github.com/milaboratory/mixcr/releases/tag/v2.1.1

**Comment by muktad** [comment]
Ok. Thanks. I will rerun them..
