### ISSUE TITLE
How is the cumulative abundance calculated in stacked Overlap pair analysis?

### ISSUE THREAD

**Issue by muktad** [mikessh/vdjtools#66]
I am getting negative values with the Overlap analysis. Can you please explain?

**Comment by mikessh** [comment]
What do you mean by cumulative frequency? The frequency in joined samples? Please provide an example (e.g. the line of output file with negative value)

**Comment by muktad** [comment]
In overlap pair analysis, the output file with the prefix 'out_paired.strict.table.collapsed' has a negative value for samples. This results in the proportion on the y axis (calculated as cumulative abundance
[1013_2.paired.strict.table.collapsed.pdf](https://github.com/mikessh/vdjtools/files/877087/1013_2.paired.strict.table.collapsed.pdf)
[1013_2.paired.strict.table.collapsed.pdf](https://github.com/mikessh/vdjtools/files/877089/1013_2.paired.strict.table.collapsed.pdf)

) in the stacked graph to be not from 0-100. Please see attached fig.

**Comment by mikessh** [comment]
Indeed this one looks strange. Its hard to tell the reason without seeing the underlying files. 

Note that VDJtools creates an R script in the folder you've executed your command. In your case the script should contain ``intersect_pair_area.r`` in its name. It will also contain absolute paths to the output files so you can execute/debug it in R/RStudio.

**Comment by muktad** [comment]
I filtered non functional aa seq and that seemed to fix the prob!
