### ISSUE TITLE
PlotFancySpectratype failed.

### ISSUE THREAD

**Issue by suntaosimon** [mikessh/vdjtools#67]
The figure can not be generated. I used the default command and only got the TXT files. I saw the error message about "[ERROR] Loading required package: ggplot2" but I have checked my Rpackage that I have ggplot2 folder in it.

PlotFancySpectratype --plot-type png PBMC.txt PBMC
Executing com.antigenomics.vdjtools.basic.PlotFancySpectratype --plot-type png PBMC.txt PBMC
[Thu Mar 30 21:44:43 CST 2017 PlotFancySpectratype] Reading sample
[Thu Mar 30 21:44:43 CST 2017 SampleStreamConnection] Loading sample PBMC
[Thu Mar 30 21:44:44 CST 2017 ClonotypeStreamParser] Finished parsing 24327 lines. 1 header and 0 bad line(s) were skipped. Bad line statistics: NO_CDR3NT=0, NO_CDR3AA=0, NO_V=0, NO_J=0, ZERO_COUNT=0, ZERO_FREQ=0, BAD_LINE=0
[Thu Mar 30 21:44:44 CST 2017 SampleStreamConnection] Loaded sample PBMC with 24327 clonotypes and 52038 cells. Memory usage: 0 of 17 GB
[Thu Mar 30 21:44:44 CST 2017 PlotFancySpectratype] Writing output and plotting data
[RUtil] Executing Rscript fancy_spectratype.r PBMC.fancyspectra.txt PBMC.fancyspectra.png Clonotype TRUE
[ERROR] Loading required package: ggplot2
Loading required package: reshape
Loading required package: RColorBrewer

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(name)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(loadNamespace(name), error = function(e) stop(e))
 8: getNamespace(ns)
 9: asNamespace(ns)
10: getExportedValue(pkg, name)
11: digest::digest
12: eval(expr, envir, enclos)
13: eval(substitute(expr), data, enclos = parent.frame())
14: with.default(guide, digest::digest(list(title, key$.label, direction,     name)))
15: with(guide, digest::digest(list(title, key$.label, direction,     name)))
16: guide_train.legend(guide, scale)
17: guide_train(guide, scale)
18: guides_train(scales = scales, theme = theme, guides = guides,     labels = labels)
19: build_guides(plot$scales, plot$layers, plot$mapping, position,     theme, plot$guides, plot$labels)
20: ggplot_gtable(data)
21: print.ggplot(x)
22: function (x, ...) UseMethod("print")(x)
An irrecoverable exception occurred. R is aborting now ...

I have checked http://stackoverflow.com/questions/25672974/caught-segfault-error-in-r but I dont quit get the solution. I am not an R guy.

**Comment by mikessh** [comment]
Have you tried ``VDJtools RInstall`` in console and ``install.packages("ggplot2")`` in R? 

This is definitely a (quite common) problem with how your R and R packages are installed, e.g. multiple R versions.

**Comment by suntaosimon** [comment]
Yes, I have tried VDJtools RInstall and ggplot2 was there but have the same problem. 
Right, I have installed my own R, do I need to uninstall my own R?

**Comment by suntaosimon** [comment]
I have also uninstalled my R and did another VDJtools RInstall, still the same problem. 

How do I uninstall VDJtools clearly? I want to reinstall vdjtools and try again.

**Comment by suntaosimon** [comment]
I think I have fixed this problem. As mikessh says, it's the R conflict when you install the your R with R-3.3.3.pkg (which there will be a R app in your Application folder) .

My solution is, uninstall R 
simply run (use /usr/local/bin for El Capitan and Sierra):
_sudo rm -rf /Library/Frameworks/R.framework /Applications/R.app \
   /usr/bin/R /usr/bin/Rscript_
you will not see the R app in your application. Check if it's uninstalled by checking under VDJTOOLS folder with "Rscript --version", make sure you see "[ERROR] Rscript not found, looks like R is not installed"
Then, install R with homebrew, 
_brew tap homebrew/science
brew install r_

Again, run Rscript --version
"R scripting front-end version 3.3.3 (2017-03-06)"
and there will not have a R app in your application folder.

Run PlotFancySpectratype and no more errors. 

If you still need to use R app, you can use RStudio https://www.rstudio.com/products/rstudio/download/
This application is not conflict with VDJTOOLS.

I am not a bioinformatics person and this is my solution, maybe not the best way but it works for me.
