### ISSUE TITLE
ggplot2 problem.

### ISSUE THREAD

**Issue by uchicagoxiao** [mikessh/vdjtools#71]
anything with ggplot2 package is not working, newly installed with vdjtools1.1.4 

Please help!

Thanks!

$vdjtools PlotFancyVJUsage --plot-type png CarT.txt CarT
Executing com.antigenomics.vdjtools.basic.PlotFancyVJUsage --plot-type png CarT.txt CarT
[Tue Apr 18 20:19:00 CDT 2017 PlotFancyVJUsage] Reading sample
[Tue Apr 18 20:19:00 CDT 2017 SampleStreamConnection] Loading sample CarT
[Tue Apr 18 20:19:02 CDT 2017 ClonotypeStreamParser] Finished parsing 26841 lines. 1 header and 0 bad line(s) were skipped. Bad line statistics: NO_CDR3NT=0, NO_CDR3AA=0, NO_V=0, NO_J=0, ZERO_COUNT=0, ZERO_FREQ=0, BAD_LINE=0
[Tue Apr 18 20:19:02 CDT 2017 SampleStreamConnection] Loaded sample CarT with 26841 clonotypes and 38153 cells. Memory usage: 0 of 0 GB
[Tue Apr 18 20:19:02 CDT 2017 SegmentUsage] Processing sample CarT
[Tue Apr 18 20:19:03 CDT 2017 PlotFancyVJUsage] Writing output
[Tue Apr 18 20:19:03 CDT 2017 PlotFancyVJUsage] Plotting data (be patient, complex graphics)
[RUtil] Executing Rscript vj_pairing_plot.r CarT.fancyvj.wt.txt CarT.fancyvj.wt.png
null device 
          1 
[Tue Apr 18 20:19:17 CDT 2017 PlotFancyVJUsage] Finished
Xiaos-MacBook-Air-3:1.1.4 Xiao$ vdjtools PlotFancySpectratype -plot-type png CarT.txt CarT
Executing com.antigenomics.vdjtools.basic.PlotFancySpectratype -plot-type png CarT.txt CarT
[Tue Apr 18 20:19:41 CDT 2017 PlotFancySpectratype] Reading sample
[Tue Apr 18 20:19:41 CDT 2017 SampleStreamConnection] Loading sample CarT
[Tue Apr 18 20:19:43 CDT 2017 ClonotypeStreamParser] Finished parsing 26841 lines. 1 header and 0 bad line(s) were skipped. Bad line statistics: NO_CDR3NT=0, NO_CDR3AA=0, NO_V=0, NO_J=0, ZERO_COUNT=0, ZERO_FREQ=0, BAD_LINE=0
[Tue Apr 18 20:19:43 CDT 2017 SampleStreamConnection] Loaded sample CarT with 26841 clonotypes and 38153 cells. Memory usage: 0 of 0 GB
[Tue Apr 18 20:19:44 CDT 2017 PlotFancySpectratype] Writing output and plotting data
[RUtil] Executing Rscript fancy_spectratype.r CarT.fancyspectra.txt CarT.fancyspectra.png Clonotype TRUE
[ERROR] Loading required package: ggplot2

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 7: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 8: loadNamespace(package, lib.loc)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
13: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
14: library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,     warn.conflicts = warn.conflicts, quietly = quietly)
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch(library(package, lib.loc = lib.loc, character.only = TRUE,     logical.return = TRUE, warn.conflicts = warn.conflicts, quietly = quietly),     error = function(e) e)
19: require(ggplot2)
An irrecoverable exception occurred. R is aborting now ...

**Comment by mikessh** [comment]
What is your R version? Most likely this has something to do with R and installed packages, not VDJtools

**Comment by mikessh** [comment]
Also try simply loading ggplot2 in R promt:

* Type ``R`` in console to access the R REPL
* Type ``library(ggplot2)`` and see if it loads succesfully

if the library doesn't load and gives the same error message - there are some problems with your R installation

**Comment by mimisikai** [comment]
R version 3.4.0. All packages that vdjtool requires have been installed. 
Also try the R in console and load ggplot2 library, R can be accessed, and ggplot2 load successfully. 
Reinstall the R and all packages, the error still show up.

**Comment by mikessh** [comment]
Have you tried to clear ``Rpackages/`` folder in VDJtools install directory?

**Comment by mimisikai** [comment]
Sorry, I’m not familiar with Mac terminal to track install directory. I used “Homwbrew” to complete the installation. Could you brief how can I find the install path and check and clear Rpackages in that directory? Thank you so much.

**Comment by suntaosimon** [comment]
My solution is, uninstall R
simply run (use /usr/local/bin for El Capitan and Sierra):
sudo rm -rf /Library/Frameworks/R.framework /Applications/R.app 
/usr/bin/R /usr/bin/Rscript
you will not see the R app in your application. Check if it's uninstalled by checking under VDJTOOLS folder with "Rscript --version", make sure you see "[ERROR] Rscript not found, looks like R is not installed"
Then, install R with homebrew,
brew tap homebrew/science
brew install r

Again, run Rscript --version
"R scripting front-end version 3.3.3 (2017-03-06)"
and there will not have a R app in your application folder.

Run PlotFancySpectratype and no more errors.

If you still need to use R app, you can use RStudio https://www.rstudio.com/products/rstudio/download/
This application is not conflict with VDJTOOLS.

I am not a bioinformatics person and this is my solution, maybe not the best way but it works for me.

**Comment by mikessh** [comment]
This seems like a valid solution. The R from homebrew is fully functional and I would prefer this to other types of R installation on macos.

**Comment by mimisikai** [comment]
Dear all,

 

The problem has been solved by following your instructions.  Thank you so much. 

 

Joe
