### ISSUE TITLE
 PlotFancySpectratype y-axis more than frequency=1

### ISSUE THREAD

**Issue by SolaimanR** [mikessh/vdjtools#75]
Hey,

when using " PlotFancySpectratype" we get some clones that have a frequency of 1.5. Shouldnt the y-axis only be able to go to 1.0, or am I interpreting the results wrong?

Thank you

**Comment by SolaimanR** [comment]
cant find any options to change, how exactly is the y-axis determined?

**Comment by SolaimanR** [comment]
Still couldnt figure this out, is there any other information i could provide so you guys can have a look?

**Comment by mikessh** [comment]
Hi, you can provide the sample (clonotype table) and the text output of PlotFancySpectratype. For the former, you can send it to me by e-mail (first name dot last name, gmail) if you don't want to post it here.

**Comment by mikessh** [comment]
Hi, can you please try once more with [this updated version](https://github.com/mikessh/vdjtools/files/1073577/vdjtools-1.1.5-SNAPSHOT.jar.zip)? you should replace the original jar with this one

**Comment by SolaimanR** [comment]
Thank you Mikhail! I was indeed using an older version!
