### ISSUE TITLE
character could not show completely

### ISSUE THREAD

**Issue by mimisikai** [mikessh/vdjtools#76]
[10.intersect.batch.aa.pdf](https://github.com/mikessh/vdjtools/files/1003182/10.intersect.batch.aa.pdf)

In the plot, if you look the top title carefully, you can see the character "t","f","d", can not be shown completely. I assume the plot size parameter setting has the problem.

**Comment by suntaosimon** [comment]
Also, in PlotQuantileStats, some clone names (aa sequence) could not shown completely.
![image](https://user-images.githubusercontent.com/3598340/26955775-9aa1df58-4c7e-11e7-816b-e70c5751ec05.png)

**Comment by mikessh** [comment]
Its totally impossible to guess correct font sizes for all cases. So you can modify the R scripts that are generated by VDJtools (see vdjtools docs). Or you can use any vector graphics editor to increase the canvas size, those letters are actually just hidden by the plot bounds, but they are still there.
