### ISSUE TITLE
Allow CDR3 nucleotide sequences with Ns

### ISSUE THREAD

**Issue by mikessh** [mikessh/vdjtools#78]

**Comment by janihuuh** [comment]
From Adaptive, if the data is produced with a TCRB-FFPE assay which is designed to work with FFPE samples but which sometimes produces sequencing where a clear base call is not possible.  In the locations where the base call is not clear, an ambiguous-nucleotide code is used (https://www.bioinformatics.org/sms/iupac.html) and we see these kind of calls in our samples (e.g. nucleotide "S" which results in an error. Calling the amino acids works with no problem in most of the sequences.

However, vdjtools refuses to work with this kind of data in every analysis module, even though you don't want to work with nucleotide sequences.
