### ISSUE TITLE
why plotfancyspectratype has a "minus number"?

### ISSUE THREAD

**Issue by suntaosimon** [mikessh/vdjtools#85]
Dear Shugay,
I have noticed a question for many times that, sometimes we see a minus number in plotfancyspectratype plots and txt files. Could you please help to explain how could this happen?
Thanks!!

![image](https://user-images.githubusercontent.com/3598340/30245413-4747874a-959e-11e7-9ff3-d1f0d1f01679.png)
![image](https://user-images.githubusercontent.com/3598340/30245414-5096e5d4-959e-11e7-8fe3-cf034695e6d5.png)
I also have tried to use vdjviz to plot the same vdjtools data, which is perfectly right(include all the frequency numbers). 
![image](https://user-images.githubusercontent.com/3598340/30246343-b10f061c-95bc-11e7-9e2f-792eefd9fb9d.png)

I have also tried version 1.1.4. It seems like this is a bug of 1.1.5. The "other" value is not calculated correctly. 
`spectraMatrix[bin][0] = spectraMatrix[bin][0] - it.freq`
But in version 1.1.4, the "other" value is not calculated correctly either(0.127977218). The vdjviz calculation is right(0.06931). 
![image](https://user-images.githubusercontent.com/3598340/30246473-b68daf36-95c0-11e7-9285-52cb7516c270.png)

**Comment by mikessh** [comment]
You are right, the subtraction from the "other" is done twice. Will fix it asap
