### ISSUE TITLE
sampling.p meaning

### ISSUE THREAD

**Issue by SolaimanR** [mikessh/vdjtools#88]
Hey,

when running the OverlapPair command the output includes a column that says "sampling.p". We were wondering how to interpret the number. We were thinking a p-value, however, when we run the same samples through the JoinSamples command to get the venndiagram, the numbers differ. We were thinking they should be the same as we are looking at the CDR3 clonotypes that overlap.

Could you give us a description of what the column represents?

Thank you.

**Comment by suntaosimon** [comment]
I also noticed that, when running JoinSamples, the frequency of a joint clonotype at corresponding sample is different from the true frequency number from the original data. But the frequency number from OverlapPair is as same as the original data. I guess the JoinSamples pipeline has bugs?

Plus, the geometric mean data from both JoinSamples and OverlapPair are different and they are both different  from manually calculation by excel.

**Comment by mikessh** [comment]
@SolaimanR The ``sampling.p`` column is experimental and should not be taken into account. Join samples and paired overlap have a different default value for clonotype grouping option (``-i``)

**Comment by mikessh** [comment]
@suntaosimon 
> I also noticed that, when running JoinSamples, the frequency of a joint clonotype at corresponding sample is different from the true frequency number from the original data. But the frequency number from OverlapPair is as same as the original data. I guess the JoinSamples pipeline has bugs?

See above, the default clonotype grouping parameter is different for these two routines. If you think there is a bug please consider providing more detailed info.. or at least read carefully the help message for both commands :)

> Plus, the geometric mean data from both JoinSamples and OverlapPair are different and they are both different from manually calculation by excel.

Can you please provide example datasets where you have encountered the difference

**Comment by suntaosimon** [comment]
looks like they are both > Defaults to strict 
(from the docs)

**Comment by mikessh** [comment]
OK, this should be wrong in the docs then, sorry :) It is better to always refer to the help output from console. Just for reference:


```
Executing com.antigenomics.vdjtools.operate.JoinSamples
At least 2 sample files should be provided if not using -m
usage: JoinSamples [options] [sample1 sample2 sample3 ... if -m is not
                   specified] output_prefix
 -c,--compress                  Compress output sample files.
 -h                             display help message
 -i,--intersect-type <string>   Intersection rule to apply. Allowed
                                values:
                                nt,ntV,ntVJ,aa,aaV,aaVJ,aa!nt,strict. Will
                                use 'aa' by default.
 -m,--metadata <filename>       Metadata file. First and second columns
                                should contain file name and sample id.
                                Header is mandatory and will be used to
                                assign column names for metadata.If column
                                named 'time' is present, it will be used
                                to specify time point sequence.
 -p,--plot                      [plotting] Turns on plotting.
    --plot-type <pdf|png>       Plot output format [default=pdf]
 -x,--times-detected <int>      Minimal number of samples where clonotype
                                should be detected. [default = 2]
```

```
Executing com.antigenomics.vdjtools.overlap.OverlapPair
usage: OverlapPair [options] sample1 sample2 output_prefix
 -c,--compress                  Compress output sample files.
 -h                             display help message
 -i,--intersect-type <string>   Intersection rule to apply. Allowed
                                values:
                                nt,ntV,ntVJ,aa,aaV,aaVJ,aa!nt,strict. Will
                                use 'strict' by default.
 -p,--plot                      Generate a scatterplot to characterize
                                overlapping clonotypes. Also generate
                                abundance difference plot if -c option is
                                specified. (R installation with ggplot2,
                                grid and gridExtra packages required).
    --plot-area-v2              Use alternative stacked area plot.
    --plot-type <pdf|png>       Plot output format [default=pdf]
 -t,--top <arg>                 Number of top clonotypes which will be
                                provided in the collapsed joint table and
                                shown on the summary stacked area plot.
                                Values > 100 are not allowed, as they
                                would make the plot unreadable. [default =
                                20]
```

**Comment by suntaosimon** [comment]
Thanks!  Got you! : )
I'm making the example dataset screenshots now.

**Comment by mikessh** [comment]
Its better to provide them as text though (and upload to issues as an attachment) Thanks

**Comment by suntaosimon** [comment]
They are over 17mb, I don't if I could upload the large files. I will try. But please see the screenshots first. 

`JoinSamples -x 1 VDJTOOLS/A.txt VDJTOOLS/B.txt 
`
For the join.aa.table.txt I have sorted the Sample A column from the largest to smallest. 
![image](https://user-images.githubusercontent.com/3598340/31308115-66dfd17c-ab36-11e7-9d21-0813b16b4543.png)

![image](https://user-images.githubusercontent.com/3598340/31308142-ee069960-ab36-11e7-8fdb-9b4c9588dc68.png)

I have set -x 1, but I still noticed there are some clonetypes from sample A is missing.

**Comment by suntaosimon** [comment]
[Archive.zip](https://github.com/mikessh/vdjtools/files/1364640/Archive.zip)
I have compressed the datasets here. Please take a look. 

Thanks!

**Comment by mikessh** [comment]
I think the reason is that these geometric mean frequencies are then normalized to sum to 1. I.e. if you compute all geometric means using excel and then divide them by their sum you'll get VDJtools estimates. 
PS It worked for me using your same file

**Comment by suntaosimon** [comment]
I got it. Thanks!

U have tried using the same command and got the right frequency? The same frequency for each clonetype in join.aa.table and VDJTOOLS raw data? For example, the first clone, "CASSSWDRDNSPLHF", join.aa.table has the frequency of 0.056901929 in join.aa.table too (not 
0.070402852)?

We have using our own pipeline (by R) to compare the 2 sample's clonetype (top100) frequency and got the results in the attachment. 
[top100_subj_A_obj_B.xlsx](https://github.com/mikessh/vdjtools/files/1364661/top100_subj_A_obj_B.xlsx)

**Comment by suntaosimon** [comment]
I think this issue can be closed. 

JoinSamples uses 'aa' by default, the same aa with different nt will be combined, thus the frequency number is different.
