### ISSUE TITLE
Convert from Immunoseq troubleshooting

### ISSUE THREAD

**Issue by MathildeFogPerez** [mikessh/vdjtools#91]
Dear Misha,

I tried to convert ImmunoSeq files but I got the following ERROR:  Some mandatory columns are absent in the input file. I tried both option -S immunoseqv2 and -S immunoseq.

Here the header of my sample files:
nucleotide	aminoAcid	count (templates)	frequencyCount (%)	cdr3Length	vMaxResolved	vFamilyName	vGeneName	vGeneAllele	vFamilyTies	vGeneNameTies	vGeneAlleleTies	dMaxResolved	dFamilyName	dGeneName	dGeneAllele	dFamilyTies	dGeneNameTies	dGeneAlleleTies	jMaxResolved	jFamilyName	jGeneName	jGeneAllele	jFamilyTies	jGeneNameTies	jGeneAlleleTies	vDeletion	n1Insertion	d5Deletion	d3Deletion	n2Insertion	jDeletion	vIndex	n1Index	dIndex	n2Index	jIndex	estimatedNumberGenomes	sequenceStatus	cloneResolved	vOrphon	dOrphon	jOrphon	vFunction	dFunction	jFunction	fractionNucleated

Thanks a lot in advance for you help.
best,
Mathilde

**Comment by MathildeFogPerez** [comment]
Dear Misha,

I also tried to run the example data you provide from  Spreafico R et al. Ann Rheum Dis. 2014. But it does not work neither.
Maybe I am doing something wrong, please let me know.
best,
Mathilde

**Comment by mikessh** [comment]
Hello, the format is ``immunoseqV2``. The problem is that one of the columns is named ``count (templates)`` instead of ``count (templates/reads)``. If you can replace/fix the header it should work

**Comment by MathildeFogPerez** [comment]
Great! It is working. Thank you Misha.
