### ISSUE TITLE
tcR vs VDJtools

### ISSUE THREAD

**Issue by malisas** [mikessh/vdjtools#92]
Both tcR and VDJtools accomplish some of the same tasks, and many of the authors are the same. Do people have an opinion about which software is better to use?

**Comment by mikessh** [comment]
If you prefer to work in command line - VDJtools. If you like working in R from the beginning - tcR. Some computationally-intensive tasks like pooling 100 repertoires with 1mln clonotypes each/joining samples/etc - better in VDJtools as it has Java backend (not much C/C++ optimization in tcR).

**Comment by malisas** [comment]
Thank you! Aside from usability, are there certain features which are available in one software but not the other?

**Comment by mikessh** [comment]
The basic features like spectratype, V/J usage, diversity estimation are more or less the same. The advanced ones are different, e.g. custom diversity measures, CDR3 features and sample pooling are present in VDJtools... its hard to list them all, better check out the manual http://vdjtools-doc.readthedocs.io/en/latest/intro.html and see if the feature you're interested in is there.

**Comment by malisas** [comment]
Ok sounds good, thanks.
